const dogFoodRatings = [
  { title: "4Health Puppy Formula Dog Food Dry", rating: 5 },
  { title: "4Health Small Bites Formula Dog Food Dry", rating: 5 },
  { title: "4Health Large Breed Formula Dog Food Dry", rating: 4.5 },
  { title: "4Health Chicken and Rice Formula Dog Food Dry", rating: 5 },
  { title: "4Health Salmon and Potato Formula Dog Food Dry", rating: 4.5 },
  { title: "4Health Performance Formula Dog Food Dry", rating: 5 },
  { title: "4Health Mature Adult Formula Dog Food Dry", rating: 3 },
  { title: "4Health Lamb and Rice Formula Dog Food Dry", rating: 3.5 },
  { title: "4Health Healthy Weight Formula Dog Food Dry", rating: 3 },
  { title: "4Health Beef and Rice Formula Dog Food Dry", rating: 4.5 },
  { title: "4Health Large Breed Puppy Dog Food Dry", rating: 5 },
  { title: "4Health Grain Free Large Breed", rating: 4 },
  { title: "4Health Grain Free Puppy", rating: 4.5 },
  { title: "4Health Grain Free Beef and Potato", rating: 3.5 },
  { title: "4Health Grain Free Duck and Potato", rating: 4 },
  { title: "4Health Grain Free Whitefish and Potato", rating: 4 },
  { title: "4Health Grain Free Small Breed", rating: 4.5 },
  { title: "4Health Grain Free Chicken and Vegetables", rating: 4 }
  { title: "4Health Untamed Wild River Recipe", rating: 4 },
  { title: "4Health Untamed Red Canyon Recipe", rating: 4 },
  { title: "4Health Untamed Open Highland Recipe", rating: 4 },
  { title: "4Health Untamed Southern Bayou Recipe", rating: 4 },
  { title: "A Pup Above Texas Beef Stew Grain Free", rating: 5 },
  { title: "A Pup Above Turkey Pawella", rating: 5 },
  { title: "A Pup Above Porky’s Luau Grain Free", rating: 5 },
  { title: "A Pup Above Chicka Chicka Bow Wow", rating: 5 },
  { title: "A Pup Above Chicka Pupatouille", rating: 4.5 },
  { title: "A Pup Above Beef Pot Roast", rating: 4.5 },
  { title: "A Pup Above Porky’s Porchetta", rating: 4.5 },
  { title: "A Pup Above Turkey Pilaf", rating: 4.5 }
];
