const dogFoodRatings = [
  { title: "4Health Puppy Formula Dog Food Dry", rating: 5 },
  { title: "4Health Small Bites Formula Dog Food Dry", rating: 5 },
  { title: "4Health Large Breed Formula Dog Food Dry", rating: 4.5 },
  { title: "4Health Chicken and Rice Formula Dog Food Dry", rating: 5 },
  { title: "4Health Salmon and Potato Formula Dog Food Dry", rating: 4.5 },
  { title: "4Health Performance Formula Dog Food Dry", rating: 5 },
  { title: "4Health Mature Adult Formula Dog Food Dry", rating: 3 },
  { title: "4Health Lamb and Rice Formula Dog Food Dry", rating: 3.5 },
  { title: "4Health Healthy Weight Formula Dog Food Dry", rating: 3 },
  { title: "4Health Beef and Rice Formula Dog Food Dry", rating: 4.5 },
  { title: "4Health Large Breed Puppy Dog Food Dry", rating: 5 },
  { title: "4Health Grain Free Large Breed", rating: 4 },
  { title: "4Health Grain Free Puppy", rating: 4.5 },
  { title: "4Health Grain Free Beef and Potato", rating: 3.5 },
  { title: "4Health Grain Free Duck and Potato", rating: 4 },
  { title: "4Health Grain Free Whitefish and Potato", rating: 4 },
  { title: "4Health Grain Free Small Breed", rating: 4.5 },
  { title: "4Health Grain Free Chicken and Vegetables", rating: 4 }
];
